services:
  bookstore-api:
    container_name: api-container-bookstore
    image: api-image-bookstore:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    container_name: mysqldb
    image: mysql:8.4.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookstore
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10

networks:
  backend: