services:
  bookstore-api:
    container_name: api-container-bookstore
    image: api-image-bookstore
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge