services:
  bookstore-api:
    container_name: api-container-bookstore
    image: api-image-bookstore
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - backend
  mysql:
    container_name: db-container-bookstore
    image: mysql:8.4.0
    ports:
      - '3307:3306'
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: bookstore
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge