spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT:3306}/bookstore?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signerKey: uGn1btxMAz77FBExhcThICMJpEWG4fwLu6pJiwlObSIubo7ivat3KSD54PRN0467
  valid-duration: 36000 # seconds
  refreshable-duration: 720000 # seconds
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    title: Bookstore API documentation
    version: 1.0.0
    description: API for managing books in a bookstore
    server: http://localhost:${server.port}${server.servlet.context-path}
    api-docs: bookstore-api