server:
  port: 8080
  servlet:
    context-path: /bookstore

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bookstore
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signerKey: "uGn1btxMAz77FBExhcThICMJpEWG4fwLu6pJiwlObSIubo7ivat3KSD54PRN0467"
  valid-duration: 3600 # seconds
  refreshable-duration: 360000 # seconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html

open:
  api:
    title: Bookstore API documentation
    version: v1.0.0
    description: API for managing books in a bookstore
    serverUrl: http://localhost:8080/bookstore
    serverName: Server Test